import os

from dotenv import load_dotenv
from google import genai
from google.genai import types

# ------------------------------------------------------------
# Load environment variables
# ------------------------------------------------------------
# The Gemini API key is stored in the .env file rather than
# being hardcoded in the source code.
load_dotenv()


# Create a Gemini API client using the API key from .env.
client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))


# Keep the model name in one place so it can be changed easily.
MODEL_NAME = "gemini-3.6-flash"


def route_question(question):
    """
    Decide which information source is required for the user's question.

    The application has two different sources of information:

    RAG:
        Used for stable Singapore travel knowledge stored in the
        local Knowledge Base.

    MCP:
        Used for current or changing information such as weather
        forecasts and currency conversion.

    The router returns:
        RAG   -> only Knowledge Base information is required
        MCP   -> only current MCP information is required
        BOTH  -> both sources are required
    """

    # The router prompt explicitly defines the responsibility of
    # each information source. This prevents the LLM from using MCP
    # for information that should come from the Knowledge Base and
    # vice versa.
    routing_prompt = f"""
    You are a router for a Singapore travel assistant.

    Decide what information is required to answer the user's question.

    Available information sources:

    The current date will be provided with the user question.
    Use it to correctly interpret relative dates such as:
    - today
    - tomorrow
    - next week
    - this weekend

    RAG:
    Use RAG for stable Singapore travel knowledge such as:
    - attractions
    - neighbourhoods
    - transportation
    - cultural and practical tips
    - food and local experiences
    - sample itineraries
    - indoor/outdoor activities

    MCP:
    Use MCP for current or changing information such as:
    - weather forecasts
    - currency conversion

    Return ONLY one of these values:
    RAG
    MCP
    BOTH

    User question:
    {question}
    """

    # Send the routing prompt to Gemini.
    # This is a separate LLM call because routing is an explicit
    # decision in our application architecture.
    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=routing_prompt,
    )

    # Remove whitespace/newlines and normalize the result to uppercase
    # so that the orchestration code can reliably compare it with
    # "RAG", "MCP", and "BOTH".
    return response.text.strip().upper()


def select_mcp_tool(question, gemini_tools):
    """
    Ask Gemini to select an appropriate MCP tool.

    The MCP client discovers the tools exposed by the MCP server and
    converts their schemas into the format expected by Gemini.

    Gemini then decides whether one of those tools is required and,
    if so, generates a function call containing:
        - tool name
        - tool arguments
    """

    # The available MCP tool definitions are supplied to Gemini.
    #
    # Gemini can therefore generate a structured function call instead
    # of us hardcoding which tool should be used for every question.
    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=question,
        config=types.GenerateContentConfig(
            tools=[types.Tool(function_declarations=gemini_tools)]
        ),
    )

    # The raw Gemini response is returned to the orchestration layer.
    # get_tool_call() is responsible for extracting the function call
    # from this response.
    return response


def get_tool_call(response):
    """
    Extract the MCP function call generated by Gemini.
    Returns: (tool_name, tool_arguments)
    Example:
        (
            "get_weather",
            {
                "latitude": 1.3521,
                "longitude": 103.8198,
                "start_date": "2026-09-21",
                "end_date": "2026-09-23"
            }
        )

    If Gemini does not request a tool: (None, None)
    """

    # Gemini may return multiple content parts. We inspect each part
    # to find a function_call.
    for part in response.candidates[0].content.parts:

        # A function_call indicates that Gemini wants the application
        # to execute one of the available MCP tools.
        if part.function_call:

            function_call = part.function_call

            # Convert the generated arguments into a normal Python
            # dictionary before returning them to the MCP client.
            return (
                function_call.name,
                dict(function_call.args),
            )

    # No function call means that Gemini did not select an MCP tool.
    return None, None


def generate_final_answer(prompt):
    """
    Generate the final response shown to the user.

    By this point, the application has already:
        1. Determined whether RAG/MCP/BOTH are required.
        2. Retrieved relevant Knowledge Base information.
        3. Retrieved current information from MCP when required.

    The final prompt combines those results and instructs Gemini
    to produce a grounded answer.
    """

    # The final prompt is constructed by assistant.py.
    # It contains the user question, conversation history,
    # RAG context, MCP results, and grounding instructions.
    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
    )

    # Return only the generated text to the caller.
    return response.text
